### ISSUE TITLE
Extend profile

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#10]
company name
twitter

**Comment by soniCaH** [comment]
- First Name
- Last Name
- Organization (Company name)
- Job Title
- Interest

are already fields present in the COD Base feature, so I propose using them (and not introduce a new one for company name). Otherwise either this feature needs to be disabled, or the feature will be overridden all the time

**Comment by woutersf** [comment]
akkoord
